/*Dados para a tabela agencia.*/
INSERT INTO agencia(NomeAgencia) values ("Agencia1");
INSERT INTO agencia(NomeAgencia) values ("Agencia2");
INSERT INTO agencia(NomeAgencia) values ("Agencia3");
INSERT INTO agencia(NomeAgencia) values ("Agencia4");
INSERT INTO agencia(NomeAgencia) values ("Agencia5");
INSERT INTO agencia(NomeAgencia) values ("Agencia6");
INSERT INTO agencia(NomeAgencia) values ("Agencia7");
INSERT INTO agencia(NomeAgencia) values ("Agencia8");
INSERT INTO agencia(NomeAgencia) values ("Agencia9");
INSERT INTO agencia(NomeAgencia) values ("Agencia10");
INSERT INTO agencia(NomeAgencia) values ("Agencia11");
INSERT INTO agencia(NomeAgencia) values ("Agencia12");
INSERT INTO agencia(NomeAgencia) values ("Agencia13");
INSERT INTO agencia(NomeAgencia) values ("Agencia14");
INSERT INTO agencia(NomeAgencia) values ("Agencia15");
INSERT INTO agencia(NomeAgencia) values ("Agencia16");
INSERT INTO agencia(NomeAgencia) values ("Agencia17");
INSERT INTO agencia(NomeAgencia) values ("Agencia18");
INSERT INTO agencia(NomeAgencia) values ("Agencia19");
INSERT INTO agencia(NomeAgencia) values ("Agencia20");
INSERT INTO agencia(NomeAgencia) values ("Agencia21");
INSERT INTO agencia(NomeAgencia) values ("Agencia22");
INSERT INTO agencia(NomeAgencia) values ("Agencia23");
INSERT INTO agencia(NomeAgencia) values ("Agencia24");
INSERT INTO agencia(NomeAgencia) values ("Agencia25");
INSERT INTO agencia(NomeAgencia) values ("Agencia26");
INSERT INTO agencia(NomeAgencia) values ("Agencia27");
INSERT INTO agencia(NomeAgencia) values ("Agencia28");
INSERT INTO agencia(NomeAgencia) values ("Agencia29");


/*Dados para a tabela apartamento.*/
INSERT INTO apartamento(numero, andar) values ("N1", "A1");
INSERT INTO apartamento(numero, andar) values ("N2", "A2");
INSERT INTO apartamento(numero, andar) values ("N3", "A3");
INSERT INTO apartamento(numero, andar) values ("N4", "A4");
INSERT INTO apartamento(numero, andar) values ("N5", "A5");
INSERT INTO apartamento(numero, andar) values ("N6", "A6");
INSERT INTO apartamento(numero, andar) values ("N7", "A7");
INSERT INTO apartamento(numero, andar) values ("N8", "A8");
INSERT INTO apartamento(numero, andar) values ("N9", "A9");
INSERT INTO apartamento(numero, andar) values ("N10", "A10");
INSERT INTO apartamento(numero, andar) values ("N11", "A11");
INSERT INTO apartamento(numero, andar) values ("N12", "A12");
INSERT INTO apartamento(numero, andar) values ("N13", "A13");
INSERT INTO apartamento(numero, andar) values ("N14", "A14");
INSERT INTO apartamento(numero, andar) values ("N15", "A15");
INSERT INTO apartamento(numero, andar) values ("N16", "A16");
INSERT INTO apartamento(numero, andar) values ("N17", "A17");
INSERT INTO apartamento(numero, andar) values ("N18", "A18");
INSERT INTO apartamento(numero, andar) values ("N19", "A19");
INSERT INTO apartamento(numero, andar) values ("N20", "A20");
INSERT INTO apartamento(numero, andar) values ("N21", "A21");
INSERT INTO apartamento(numero, andar) values ("N22", "A22");
INSERT INTO apartamento(numero, andar) values ("N23", "A23");
INSERT INTO apartamento(numero, andar) values ("N24", "A24");
INSERT INTO apartamento(numero, andar) values ("N25", "A25");
INSERT INTO apartamento(numero, andar) values ("N26", "A26");
INSERT INTO apartamento(numero, andar) values ("N27", "A27");
INSERT INTO apartamento(numero, andar) values ("N28", "A28");
INSERT INTO apartamento(numero, andar) values ("N29", "A29");


/*Dados para a tabela cliente.*/
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom1", "Prof1");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom2", "Prof2");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom3", "Prof3");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom4", "Prof4");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom5", "Prof5");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom6", "Prof6");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom7", "Prof7");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom8", "Prof8");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom9", "Prof9");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom10", "Prof10");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom11", "Prof11");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom12", "Prof12");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom13", "Prof13");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom14", "Prof14");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom15", "Prof15");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom16", "Prof16");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom17", "Prof17");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom18", "Prof18");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom19", "Prof19");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom20", "Prof20");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom21", "Prof21");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom22", "Prof22");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom23", "Prof23");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom24", "Prof24");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom25", "Prof25");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom26", "Prof26");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom27", "Prof27");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom28", "Prof28");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom29", "Prof29");


/*Dados para a tabela consumo.*/
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (1, 1, 1, 1, 1, "Tipo 1", "Desc 1", "Tranp 1", 1, 1);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (2, 2, 2, 2, 2, "Tipo 2", "Desc 2", "Tranp 2", 2, 2);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (3, 3, 3, 3, 3, "Tipo 3", "Desc 3", "Tranp 3", 3, 3);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (4, 4, 4, 4, 4, "Tipo 4", "Desc 4", "Tranp 4", 4, 4);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (5, 5, 5, 5, 5, "Tipo 5", "Desc 5", "Tranp 5", 5, 5);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (6, 6, 6, 6, 6, "Tipo 6", "Desc 6", "Tranp 6", 6, 6);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (7, 7, 7, 7, 7, "Tipo 7", "Desc 7", "Tranp 7", 7, 7);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (8, 8, 8, 8, 8, "Tipo 8", "Desc 8", "Tranp 8", 8, 8);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (9, 9, 9, 9, 9, "Tipo 9", "Desc 9", "Tranp 9", 9, 9);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (10, 10, 10, 10, 10, "Tipo 10", "Desc 10", "Tranp 10", 10, 10);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (11, 11, 11, 11, 11, "Tipo 11", "Desc 11", "Tranp 11", 11, 11);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (12, 12, 12, 12, 12, "Tipo 12", "Desc 12", "Tranp 12", 12, 12);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (13, 13, 13, 13, 13, "Tipo 13", "Desc 13", "Tranp 13", 13, 13);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (14, 14, 14, 14, 14, "Tipo 14", "Desc 14", "Tranp 14", 14, 14);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (15, 15, 15, 15, 15, "Tipo 15", "Desc 15", "Tranp 15", 15, 15);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (16, 16, 16, 16, 16, "Tipo 16", "Desc 16", "Tranp 16", 16, 16);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (17, 17, 17, 17, 17, "Tipo 17", "Desc 17", "Tranp 17", 17, 17);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (18, 18, 18, 18, 18, "Tipo 18", "Desc 18", "Tranp 18", 18, 18);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (19, 19, 19, 19, 19, "Tipo 19", "Desc 19", "Tranp 19", 19, 19);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (20, 20, 20, 20, 20, "Tipo 20", "Desc 20", "Tranp 20", 20, 20);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (21, 21, 21, 21, 21, "Tipo 21", "Desc 21", "Tranp 21", 21, 21);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (22, 22, 22, 22, 22, "Tipo 22", "Desc 22", "Tranp 22", 22, 22);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (23, 23, 23, 23, 23, "Tipo 23", "Desc 23", "Tranp 23", 23, 23);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (24, 24, 24, 24, 24, "Tipo 24", "Desc 24", "Tranp 24", 24, 24);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (25, 25, 25, 25, 25, "Tipo 25", "Desc 25", "Tranp 25", 25, 25);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (26, 26, 26, 26, 26, "Tipo 26", "Desc 26", "Tranp 26", 26, 26);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (27, 27, 27, 27, 27, "Tipo 27", "Desc 27", "Tranp 27", 27, 27);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (28, 28, 28, 28, 28, "Tipo 28", "Desc 28", "Tranp 28", 28, 28);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (29, 29, 29, 29, 29, "Tipo 29", "Desc 29", "Tranp 29", 29, 29);


/*Dados para a tabela hospedagem.*/
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (1, 1, 1, "Tipo 1", "Desc 1", "DesM 1", 1, 1);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (2, 2, 2, "Tipo 2", "Desc 2", "DesM 2", 2, 2);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (3, 3, 3, "Tipo 3", "Desc 3", "DesM 3", 3, 3);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (4, 4, 4, "Tipo 4", "Desc 4", "DesM 4", 4, 4);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (5, 5, 5, "Tipo 5", "Desc 5", "DesM 5", 5, 5);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (6, 6, 6, "Tipo 6", "Desc 6", "DesM 6", 6, 6);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (7, 7, 7, "Tipo 7", "Desc 7", "DesM 7", 7, 7);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (8, 8, 8, "Tipo 8", "Desc 8", "DesM 8", 8, 8);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (9, 9, 9, "Tipo 9", "Desc 9", "DesM 9", 9, 9);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (10, 10, 10, "Tipo 10", "Desc 10", "DesM 10", 10, 10);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (11, 11, 11, "Tipo 11", "Desc 11", "DesM 11", 11, 11);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (12, 12, 12, "Tipo 12", "Desc 12", "DesM 12", 12, 12);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (13, 13, 13, "Tipo 13", "Desc 13", "DesM 13", 13, 13);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (14, 14, 14, "Tipo 14", "Desc 14", "DesM 14", 14, 14);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (15, 15, 15, "Tipo 15", "Desc 15", "DesM 15", 15, 15);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (16, 16, 16, "Tipo 16", "Desc 16", "DesM 16", 16, 16);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (17, 17, 17, "Tipo 17", "Desc 17", "DesM 17", 17, 17);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (18, 18, 18, "Tipo 18", "Desc 18", "DesM 18", 18, 18);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (19, 19, 19, "Tipo 19", "Desc 19", "DesM 19", 19, 19);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (20, 20, 20, "Tipo 20", "Desc 20", "DesM 20", 20, 20);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (21, 21, 21, "Tipo 21", "Desc 21", "DesM 21", 21, 21);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (22, 22, 22, "Tipo 22", "Desc 22", "DesM 22", 22, 22);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (23, 23, 23, "Tipo 23", "Desc 23", "DesM 23", 23, 23);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (24, 24, 24, "Tipo 24", "Desc 24", "DesM 24", 24, 24);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (25, 25, 25, "Tipo 25", "Desc 25", "DesM 25", 25, 25);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (26, 26, 26, "Tipo 26", "Desc 26", "DesM 26", 26, 26);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (27, 27, 27, "Tipo 27", "Desc 27", "DesM 27", 27, 27);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (28, 28, 28, "Tipo 28", "Desc 28", "DesM 28", 28, 28);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (29, 29, 29, "Tipo 29", "Desc 29", "DesM 29", 29, 29);


/*Dados para a tabela produto.*/
INSERT INTO produto(descricao) values ("PolettoProduto codigo 1");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 2");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 3");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 4");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 5");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 6");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 7");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 8");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 9");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 10");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 11");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 12");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 13");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 14");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 15");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 16");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 17");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 18");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 19");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 20");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 21");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 22");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 23");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 24");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 25");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 26");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 27");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 28");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 29");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 30");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 31");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 32");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 33");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 34");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 35");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 36");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 37");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 38");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 39");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 40");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 41");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 42");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 43");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 44");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 45");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 46");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 47");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 48");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 49");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 50");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 51");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 52");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 53");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 54");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 55");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 56");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 57");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 58");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 59");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 60");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 61");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 62");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 63");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 64");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 65");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 66");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 67");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 68");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 69");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 70");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 71");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 72");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 73");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 74");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 75");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 76");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 77");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 78");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 79");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 80");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 81");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 82");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 83");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 84");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 85");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 86");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 87");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 88");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 89");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 90");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 91");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 92");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 93");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 94");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 95");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 96");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 97");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 98");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 99");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 100");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 101");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 102");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 103");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 104");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 105");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 106");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 107");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 108");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 109");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 110");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 111");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 112");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 113");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 114");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 115");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 116");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 117");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 118");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 119");


/*Dados para a tabela servico.*/
INSERT INTO servico(nome_servico) values ("Servico codigo 1");
INSERT INTO servico(nome_servico) values ("Servico codigo 2");
INSERT INTO servico(nome_servico) values ("Servico codigo 3");
INSERT INTO servico(nome_servico) values ("Servico codigo 4");
INSERT INTO servico(nome_servico) values ("Servico codigo 5");
INSERT INTO servico(nome_servico) values ("Servico codigo 6");
INSERT INTO servico(nome_servico) values ("Servico codigo 7");
INSERT INTO servico(nome_servico) values ("Servico codigo 8");
INSERT INTO servico(nome_servico) values ("Servico codigo 9");
INSERT INTO servico(nome_servico) values ("Servico codigo 10");
INSERT INTO servico(nome_servico) values ("Servico codigo 11");
INSERT INTO servico(nome_servico) values ("Servico codigo 12");
INSERT INTO servico(nome_servico) values ("Servico codigo 13");
INSERT INTO servico(nome_servico) values ("Servico codigo 14");
INSERT INTO servico(nome_servico) values ("Servico codigo 15");
INSERT INTO servico(nome_servico) values ("Servico codigo 16");
INSERT INTO servico(nome_servico) values ("Servico codigo 17");
INSERT INTO servico(nome_servico) values ("Servico codigo 18");
INSERT INTO servico(nome_servico) values ("Servico codigo 19");
INSERT INTO servico(nome_servico) values ("Servico codigo 20");
INSERT INTO servico(nome_servico) values ("Servico codigo 21");
INSERT INTO servico(nome_servico) values ("Servico codigo 22");
INSERT INTO servico(nome_servico) values ("Servico codigo 23");
INSERT INTO servico(nome_servico) values ("Servico codigo 24");
INSERT INTO servico(nome_servico) values ("Servico codigo 25");
INSERT INTO servico(nome_servico) values ("Servico codigo 26");
INSERT INTO servico(nome_servico) values ("Servico codigo 27");
INSERT INTO servico(nome_servico) values ("Servico codigo 28");
INSERT INTO servico(nome_servico) values ("Servico codigo 29");


/*Dados para a tabela tempo.*/
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan1", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan2", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan3", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan4", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan5", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan6", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan7", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan8", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan9", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan10", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan11", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan12", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan13", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan14", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan15", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan16", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan17", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan18", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan19", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan20", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan21", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan22", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan23", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan24", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan25", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan26", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan27", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan28", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan29", "2015-12-25");


/* Dados para as outras tabelas */
INSERT INTO servico(nome_servico) values ("Servico codigo 1");
INSERT INTO servico(nome_servico) values ("Servico codigo 2");
INSERT INTO servico(nome_servico) values ("Servico codigo 3");
INSERT INTO servico(nome_servico) values ("Servico codigo 4");
INSERT INTO servico(nome_servico) values ("Servico codigo 5");
INSERT INTO servico(nome_servico) values ("Servico codigo 6");
INSERT INTO servico(nome_servico) values ("Servico codigo 7");
INSERT INTO servico(nome_servico) values ("Servico codigo 8");
INSERT INTO servico(nome_servico) values ("Servico codigo 9");
INSERT INTO servico(nome_servico) values ("Servico codigo 10");
INSERT INTO servico(nome_servico) values ("Servico codigo 11");
INSERT INTO servico(nome_servico) values ("Servico codigo 12");
INSERT INTO servico(nome_servico) values ("Servico codigo 13");
INSERT INTO servico(nome_servico) values ("Servico codigo 14");
INSERT INTO servico(nome_servico) values ("Servico codigo 15");
INSERT INTO servico(nome_servico) values ("Servico codigo 16");
INSERT INTO servico(nome_servico) values ("Servico codigo 17");
INSERT INTO servico(nome_servico) values ("Servico codigo 18");
INSERT INTO servico(nome_servico) values ("Servico codigo 19");
INSERT INTO servico(nome_servico) values ("Servico codigo 20");
INSERT INTO servico(nome_servico) values ("Servico codigo 21");
INSERT INTO servico(nome_servico) values ("Servico codigo 22");
INSERT INTO servico(nome_servico) values ("Servico codigo 23");
INSERT INTO servico(nome_servico) values ("Servico codigo 24");
INSERT INTO servico(nome_servico) values ("Servico codigo 25");
INSERT INTO servico(nome_servico) values ("Servico codigo 26");
INSERT INTO servico(nome_servico) values ("Servico codigo 27");
INSERT INTO servico(nome_servico) values ("Servico codigo 28");
INSERT INTO servico(nome_servico) values ("Servico codigo 29");


INSERT INTO produto(descricao) values ("PolettoProduto codigo 1");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 2");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 3");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 4");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 5");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 6");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 7");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 8");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 9");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 10");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 11");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 12");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 13");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 14");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 15");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 16");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 17");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 18");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 19");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 20");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 21");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 22");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 23");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 24");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 25");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 26");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 27");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 28");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 29");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 30");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 31");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 32");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 33");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 34");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 35");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 36");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 37");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 38");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 39");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 40");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 41");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 42");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 43");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 44");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 45");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 46");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 47");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 48");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 49");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 50");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 51");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 52");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 53");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 54");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 55");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 56");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 57");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 58");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 59");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 60");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 61");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 62");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 63");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 64");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 65");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 66");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 67");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 68");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 69");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 70");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 71");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 72");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 73");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 74");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 75");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 76");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 77");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 78");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 79");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 80");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 81");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 82");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 83");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 84");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 85");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 86");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 87");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 88");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 89");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 90");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 91");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 92");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 93");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 94");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 95");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 96");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 97");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 98");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 99");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 100");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 101");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 102");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 103");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 104");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 105");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 106");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 107");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 108");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 109");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 110");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 111");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 112");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 113");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 114");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 115");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 116");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 117");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 118");
INSERT INTO produto(descricao) values ("PolettoProduto codigo 119");


INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan1", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan2", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan3", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan4", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan5", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan6", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan7", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan8", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan9", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan10", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan11", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan12", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan13", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan14", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan15", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan16", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan17", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan18", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan19", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan20", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan21", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan22", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan23", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan24", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan25", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan26", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan27", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan28", "2015-12-25");
INSERT INTO tempo(ano, trimestre, mes, data) values ("2016", "1", "Jan29", "2015-12-25");


INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom1", "Prof1");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom2", "Prof2");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom3", "Prof3");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom4", "Prof4");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom5", "Prof5");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom6", "Prof6");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom7", "Prof7");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom8", "Prof8");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom9", "Prof9");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom10", "Prof10");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom11", "Prof11");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom12", "Prof12");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom13", "Prof13");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom14", "Prof14");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom15", "Prof15");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom16", "Prof16");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom17", "Prof17");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom18", "Prof18");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom19", "Prof19");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom20", "Prof20");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom21", "Prof21");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom22", "Prof22");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom23", "Prof23");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom24", "Prof24");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom25", "Prof25");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom26", "Prof26");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom27", "Prof27");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom28", "Prof28");
INSERT INTO cliente(nome_cliente, profissao_cliente ) values ("Nom29", "Prof29");


INSERT INTO APARTAMENTO(numero, andar) values ("N1", "A1");
INSERT INTO APARTAMENTO(numero, andar) values ("N2", "A2");
INSERT INTO APARTAMENTO(numero, andar) values ("N3", "A3");
INSERT INTO APARTAMENTO(numero, andar) values ("N4", "A4");
INSERT INTO APARTAMENTO(numero, andar) values ("N5", "A5");
INSERT INTO APARTAMENTO(numero, andar) values ("N6", "A6");
INSERT INTO APARTAMENTO(numero, andar) values ("N7", "A7");
INSERT INTO APARTAMENTO(numero, andar) values ("N8", "A8");
INSERT INTO APARTAMENTO(numero, andar) values ("N9", "A9");
INSERT INTO APARTAMENTO(numero, andar) values ("N10", "A10");
INSERT INTO APARTAMENTO(numero, andar) values ("N11", "A11");
INSERT INTO APARTAMENTO(numero, andar) values ("N12", "A12");
INSERT INTO APARTAMENTO(numero, andar) values ("N13", "A13");
INSERT INTO APARTAMENTO(numero, andar) values ("N14", "A14");
INSERT INTO APARTAMENTO(numero, andar) values ("N15", "A15");
INSERT INTO APARTAMENTO(numero, andar) values ("N16", "A16");
INSERT INTO APARTAMENTO(numero, andar) values ("N17", "A17");
INSERT INTO APARTAMENTO(numero, andar) values ("N18", "A18");
INSERT INTO APARTAMENTO(numero, andar) values ("N19", "A19");
INSERT INTO APARTAMENTO(numero, andar) values ("N20", "A20");
INSERT INTO APARTAMENTO(numero, andar) values ("N21", "A21");
INSERT INTO APARTAMENTO(numero, andar) values ("N22", "A22");
INSERT INTO APARTAMENTO(numero, andar) values ("N23", "A23");
INSERT INTO APARTAMENTO(numero, andar) values ("N24", "A24");
INSERT INTO APARTAMENTO(numero, andar) values ("N25", "A25");
INSERT INTO APARTAMENTO(numero, andar) values ("N26", "A26");
INSERT INTO APARTAMENTO(numero, andar) values ("N27", "A27");
INSERT INTO APARTAMENTO(numero, andar) values ("N28", "A28");
INSERT INTO APARTAMENTO(numero, andar) values ("N29", "A29");


INSERT INTO agencia(NomeAgencia) values ("Agencia1");
INSERT INTO agencia(NomeAgencia) values ("Agencia2");
INSERT INTO agencia(NomeAgencia) values ("Agencia3");
INSERT INTO agencia(NomeAgencia) values ("Agencia4");
INSERT INTO agencia(NomeAgencia) values ("Agencia5");
INSERT INTO agencia(NomeAgencia) values ("Agencia6");
INSERT INTO agencia(NomeAgencia) values ("Agencia7");
INSERT INTO agencia(NomeAgencia) values ("Agencia8");
INSERT INTO agencia(NomeAgencia) values ("Agencia9");
INSERT INTO agencia(NomeAgencia) values ("Agencia10");
INSERT INTO agencia(NomeAgencia) values ("Agencia11");
INSERT INTO agencia(NomeAgencia) values ("Agencia12");
INSERT INTO agencia(NomeAgencia) values ("Agencia13");
INSERT INTO agencia(NomeAgencia) values ("Agencia14");
INSERT INTO agencia(NomeAgencia) values ("Agencia15");
INSERT INTO agencia(NomeAgencia) values ("Agencia16");
INSERT INTO agencia(NomeAgencia) values ("Agencia17");
INSERT INTO agencia(NomeAgencia) values ("Agencia18");
INSERT INTO agencia(NomeAgencia) values ("Agencia19");
INSERT INTO agencia(NomeAgencia) values ("Agencia20");
INSERT INTO agencia(NomeAgencia) values ("Agencia21");
INSERT INTO agencia(NomeAgencia) values ("Agencia22");
INSERT INTO agencia(NomeAgencia) values ("Agencia23");
INSERT INTO agencia(NomeAgencia) values ("Agencia24");
INSERT INTO agencia(NomeAgencia) values ("Agencia25");
INSERT INTO agencia(NomeAgencia) values ("Agencia26");
INSERT INTO agencia(NomeAgencia) values ("Agencia27");
INSERT INTO agencia(NomeAgencia) values ("Agencia28");
INSERT INTO agencia(NomeAgencia) values ("Agencia29");


INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (1, 1, 1, 1, 1, "Tipo 1", "Desc 1", "Tranp 1", 1, 1);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (2, 2, 2, 2, 2, "Tipo 2", "Desc 2", "Tranp 2", 2, 2);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (3, 3, 3, 3, 3, "Tipo 3", "Desc 3", "Tranp 3", 3, 3);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (4, 4, 4, 4, 4, "Tipo 4", "Desc 4", "Tranp 4", 4, 4);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (5, 5, 5, 5, 5, "Tipo 5", "Desc 5", "Tranp 5", 5, 5);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (6, 6, 6, 6, 6, "Tipo 6", "Desc 6", "Tranp 6", 6, 6);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (7, 7, 7, 7, 7, "Tipo 7", "Desc 7", "Tranp 7", 7, 7);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (8, 8, 8, 8, 8, "Tipo 8", "Desc 8", "Tranp 8", 8, 8);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (9, 9, 9, 9, 9, "Tipo 9", "Desc 9", "Tranp 9", 9, 9);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (10, 10, 10, 10, 10, "Tipo 10", "Desc 10", "Tranp 10", 10, 10);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (11, 11, 11, 11, 11, "Tipo 11", "Desc 11", "Tranp 11", 11, 11);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (12, 12, 12, 12, 12, "Tipo 12", "Desc 12", "Tranp 12", 12, 12);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (13, 13, 13, 13, 13, "Tipo 13", "Desc 13", "Tranp 13", 13, 13);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (14, 14, 14, 14, 14, "Tipo 14", "Desc 14", "Tranp 14", 14, 14);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (15, 15, 15, 15, 15, "Tipo 15", "Desc 15", "Tranp 15", 15, 15);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (16, 16, 16, 16, 16, "Tipo 16", "Desc 16", "Tranp 16", 16, 16);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (17, 17, 17, 17, 17, "Tipo 17", "Desc 17", "Tranp 17", 17, 17);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (18, 18, 18, 18, 18, "Tipo 18", "Desc 18", "Tranp 18", 18, 18);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (19, 19, 19, 19, 19, "Tipo 19", "Desc 19", "Tranp 19", 19, 19);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (20, 20, 20, 20, 20, "Tipo 20", "Desc 20", "Tranp 20", 20, 20);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (21, 21, 21, 21, 21, "Tipo 21", "Desc 21", "Tranp 21", 21, 21);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (22, 22, 22, 22, 22, "Tipo 22", "Desc 22", "Tranp 22", 22, 22);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (23, 23, 23, 23, 23, "Tipo 23", "Desc 23", "Tranp 23", 23, 23);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (24, 24, 24, 24, 24, "Tipo 24", "Desc 24", "Tranp 24", 24, 24);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (25, 25, 25, 25, 25, "Tipo 25", "Desc 25", "Tranp 25", 25, 25);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (26, 26, 26, 26, 26, "Tipo 26", "Desc 26", "Tranp 26", 26, 26);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (27, 27, 27, 27, 27, "Tipo 27", "Desc 27", "Tranp 27", 27, 27);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (28, 28, 28, 28, 28, "Tipo 28", "Desc 28", "Tranp 28", 28, 28);
INSERT INTO consumos(chave_apto, cpf_cliente, chave_tempo, chave_produto, chave_servico, tipo_apartamento, descricao_motivo, descricao_meio_transp, valor_consumo, quantidade) values (29, 29, 29, 29, 29, "Tipo 29", "Desc 29", "Tranp 29", 29, 29);


INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (1, 1, 1, "Tipo 1", "Desc 1", "DesM 1", 1, 1);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (2, 2, 2, "Tipo 2", "Desc 2", "DesM 2", 2, 2);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (3, 3, 3, "Tipo 3", "Desc 3", "DesM 3", 3, 3);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (4, 4, 4, "Tipo 4", "Desc 4", "DesM 4", 4, 4);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (5, 5, 5, "Tipo 5", "Desc 5", "DesM 5", 5, 5);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (6, 6, 6, "Tipo 6", "Desc 6", "DesM 6", 6, 6);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (7, 7, 7, "Tipo 7", "Desc 7", "DesM 7", 7, 7);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (8, 8, 8, "Tipo 8", "Desc 8", "DesM 8", 8, 8);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (9, 9, 9, "Tipo 9", "Desc 9", "DesM 9", 9, 9);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (10, 10, 10, "Tipo 10", "Desc 10", "DesM 10", 10, 10);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (11, 11, 11, "Tipo 11", "Desc 11", "DesM 11", 11, 11);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (12, 12, 12, "Tipo 12", "Desc 12", "DesM 12", 12, 12);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (13, 13, 13, "Tipo 13", "Desc 13", "DesM 13", 13, 13);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (14, 14, 14, "Tipo 14", "Desc 14", "DesM 14", 14, 14);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (15, 15, 15, "Tipo 15", "Desc 15", "DesM 15", 15, 15);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (16, 16, 16, "Tipo 16", "Desc 16", "DesM 16", 16, 16);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (17, 17, 17, "Tipo 17", "Desc 17", "DesM 17", 17, 17);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (18, 18, 18, "Tipo 18", "Desc 18", "DesM 18", 18, 18);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (19, 19, 19, "Tipo 19", "Desc 19", "DesM 19", 19, 19);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (20, 20, 20, "Tipo 20", "Desc 20", "DesM 20", 20, 20);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (21, 21, 21, "Tipo 21", "Desc 21", "DesM 21", 21, 21);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (22, 22, 22, "Tipo 22", "Desc 22", "DesM 22", 22, 22);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (23, 23, 23, "Tipo 23", "Desc 23", "DesM 23", 23, 23);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (24, 24, 24, "Tipo 24", "Desc 24", "DesM 24", 24, 24);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (25, 25, 25, "Tipo 25", "Desc 25", "DesM 25", 25, 25);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (26, 26, 26, "Tipo 26", "Desc 26", "DesM 26", 26, 26);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (27, 27, 27, "Tipo 27", "Desc 27", "DesM 27", 27, 27);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (28, 28, 28, "Tipo 28", "Desc 28", "DesM 28", 28, 28);
INSERT INTO hospedagem(chave_apto, chave_agencia, cpf_cliente, tipo_de_apartamento, descricao_meio_transp, descricao_motivo, chave_tempo, valor_faturado) values (29, 29, 29, "Tipo 29", "Desc 29", "DesM 29", 29, 29);

